### ISSUE TITLE
Consider creating a "minimal viable charter" for submission to the OpenWIS Association

### ISSUE THREAD

**Issue by isedwards** [opencdms/opencdms-project#17]
The lastest version of the project charter is online here:
    https://github.com/opencdms/opencdms-project/blob/master/charter/opencdms_charter.md

This issue proposes the idea of reducing the content of the charter, for the time being, such that our future Project Management Committee make more of the key decisions on project structure and governance.

This would allow us to progress with the administation tasks that are required to formally establish OpenCDMS as a project within the association and allow us to realise some of the benefits from being an accepted project, including the use of the OpenWIS contributor's licence agreement. 

Thoughts @bruban, everyone? I personally don't have a preference either way (assuming that the OpenWIS Association allow project charters to be reopened).

I support the submission of the current charter or the submission of a minimal charter.

**Comment by bruban** [comment]
Ian,

I have had very little input in the document that has been put forward.

I have a different view on how we should structure the project to give us the best chance of success. This includes our governance.

I have discussed this before, and won’t do so again now, as I understand that it is seen as a distraction.

I’m working as quickly as I can to put together a straw man outline so that the community can see an outline of the vision that I have.

We can than discuss, and adjust proposals as required.

I honestly do not see what the rush is at this stage.

An agreement in principle to assign IP should be sufficient for now, on the understanding that contributors will be required to sign a formal agreement when appropriate. We don’t have many contributors at this stage.

Again, I urge patience.

Kind regards,

Bruce

**Comment by isedwards** [comment]
Denis circulated version 2 of the document on 13th of September.

Feedback, both on and off the list, was entirely positive.

Your feedback at the time was that you had a different view. My response was that we could consider a minimal charter in the meantime.

This was quarter of a year ago. I don't want to rush anyone, but given we've unanimously agreed to join OpenWIS we want to move forward.

Again, I urge progress.

**Comment by Steve-Palmer** [comment]
I am not sure what a "minimal" document would look like. Since the objections raised above concern project governance, then the section to reduce would be "OpenCDMS Project Structure and Initial Governance" - note the word "Initial" - this means it is not graven on tablets of stone but can be changed as needed. The Project Management Committee is a requirement, so the composition and functions would need to remain. It would be possible to remove all references to the PAT and the PTT - but then there would be no explanation of how the project should organise as a community.

I advise against removing the references to the PAT and PTT and therefore advise against a more "minimal" document.

**Comment by isedwards** [comment]
This issue is being addressed as part of https://github.com/opencdms/opencdms-project/issues/16#issuecomment-599575640

Closing issue.
